### ISSUE TITLE
Threshold of the Fig4A and B

### ISSUE THREAD

**Issue by YueZhang2019** [nedialkova-lab/mim-tRNAseq#14]
This is Yue from Umassmed GTC center.
 
I just found that when the pipeline polt isodecoder_countplot use “pajd<0.05” as threshold, but padj<0.01 in the Fig4A of paper. 
 
In the Fig4A, there is no threshold for foldchange?  Am I right?
 
I want to re-plot the isodecoder_countplot with my own data by R.  So which should I use 0.05 or 0.01?  and what is the threshold for foldchange?
 
Thank you so much.

**Comment by nedialkova-lab** [comment]
Hi Yue, the differential expression analysis in the mim-tRNAseq pipeline is done with DESeq2, and the threshold for statistical significance is up to the user (it is indeed padj<0.05 for the plots in the current version). You can choose how to plot the data you will find in the results tables in the DESeq2 subdirectory. We do not recommend a fold change threshold as the null hypothesis we test for is that the log2fold change between treatment and control for a gene’s expression is exactly zero. DESeq2 can also test for log2 fold change above or below a user-specified threshold (doi: 10.1186/s13059-014-0550-8).

**Comment by drewjbeh** [comment]
Hi @YueZhang2019 
Thanks for raising the issue! I will be releasing a newer minor update very shortly, which will display the appropriate adjusted p-value on these plots by default. There will also be another new parameter added that will allow the user to specify this p-value threshold at runtime. Keep an eye out for the update if you're interested!

**Comment by drewjbeh** [comment]
@YueZhang2019 I've added the code to handle this update and released the version. It should be available on bioconda in the next day or two. Please update your mimseq version to 0.3.4.2. You will then see the adjusted p-value displayed on the plots as in the image, and will be able to specify a threshold for this with `--p-adj`
![Screenshot 2021-06-22 at 20 22 51](https://user-images.githubusercontent.com/11058365/122979271-a499d700-d397-11eb-9d2e-a1bc0f1d59e9.png)
