### ISSUE TITLE
nothing provides pyfiglet needed by mimseq-0.2.5.3-pyr40_0

### ISSUE THREAD

**Issue by MKoesters** [nedialkova-lab/mim-tRNAseq#17]
Hi all,

I'm trying to install mimseq on a CenOS server.
When following the installation instructions, I run into an error when executing

`mamba install -c bioconda mimseq`

```

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.15.3) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['mimseq']

bioconda/linux-64        Using cache
bioconda/noarch          Using cache
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change

Pinned packages:
  - python 3.7.*


Encountered problems while solving:
  - nothing provides pyfiglet needed by mimseq-0.2.5.3-pyr40_0
  
```

Installing pyfiglet using pip does not resolve the error.
Is compatible with CentOS?
If so, how could I resolve this installation problems without installing all dependencies by hand?

Best,
Manuel

**Comment by drewjbeh** [comment]
Hi there,

pyfiglet is a conda-forge package. It seems you don't have conda-forge as a channel added. Please try `conda config --add channels conda-forge` and try again. You should then see this channel after "Looking for: ['mimseq']" somewhere. 

On another note, the error seems to indicate that mimseq v0.2.5.3 is trying to be compiled and installed. That's a really really old version. It should be something more like 0.3.4.3. Please be aware of this when you get the installation to work. You may need to update!

**Comment by MKoesters** [comment]
That solved my issue, thanks!
