### ISSUE TITLE
question in CCAanalysis output

### ISSUE THREAD

**Issue by oneleaf425** [nedialkova-lab/mim-tRNAseq#24]
Hello! I used the mimseq computational tool v0.3.3.2 in our tRNA-seq analyzing. I plan to use the results of CCAanalysis in mimseq outputs. But I have a problem in the outputs. In the output file "CCAcounts.csv", does 'absent' tRNA counts mean the 3'end locate just at -1 bp of CCA, or include all 3'end truncated tRNAs (3'end at -2, -3, -4 .... of CCA)? It is very important to us because we only wanted to use the tRNAs that end just at 1 bp before CCA.

Looking forward to your reply. Thank you so much!

**Comment by drewjbeh** [comment]
HI there. CCA analysis is done per read by comparing the most 3' mapped position of the read against the 3' position of the reference. For "Absent", we count all reads that begin alignment at position -1 from CCA or anywhere 5' of this (i.e including all truncated reads that map upstream of -1 as well). You can see the code for this [here](https://github.com/nedialkova-lab/mim-tRNAseq/blob/6fdc6ee5d9a79e6862075f75feeeaa425226c884/mimseq/mmQuant.py#L225). You could write a similar smaller piece of code and change that `elif ref_pos <= ref_length - 3:` to be `elif ref_pos = ref_length - 3:` without the "<" sign to only count -1 mapping reads. With [pysam](https://pysam.readthedocs.io/en/latest/api.html) it is easy to read in the bam file, loops through all reads and count them as I have in `mmQuant.py`. Unfortunately, you will loose out on the deconvolution and assignment of reads to tRNA transcripts by doing this yourself. 
You could of course also simply remove that "<" in your installation of mimseq and rerun your data!

**Comment by oneleaf425** [comment]
OK I will try as you suggest.
Thanks again!
