### ISSUE TITLE
Conda Installation - R version problem

### ISSUE THREAD

**Issue by cyken6621** [nedialkova-lab/mim-tRNAseq#26]
Hi Drew,

I have used previous version of mimseq 0.3.x and it worked for me except for some issue that I have reported here in GitHub.

Recently, I tried to install the ver 0.4 by creating another new conda env as your instruction.
However, I found that R4.1.1 was installed in the new conda env.
The modification analysis was interrupted with error 

+------------------+
| Parsing new mods |
+------------------+
2021-12-15 16:15:54,622 [INFO ] 0 new predicted position 34 inosines
2021-12-15 16:15:54,624 [INFO ] 6 new predicted modifications
2021-12-15 16:15:54,675 [INFO ] 277 clusters filtered out according to minimum coverage threshold: 2000.0 total read coverage per isodecoder.
2021-12-15 16:16:09,646 [INFO ] Output final tables, counts and new mods...
2021-12-15 16:16:11,285 [INFO ] ** Read counts per anticodon saved to v4hg38_HEK239vsK562/counts/Anticodon_counts_raw.txt **
2021-12-15 16:16:11,285 [INFO ] ** Read counts per isodecoder saved to v4hg38_HEK239vsK562/counts/Isodecoder_counts_raw.txt **
2021-12-15 16:16:11,379 [INFO ] Plotting modification and RT stop data...
Error in library(reshape2) : there is no package called ‘reshape2’
Calls: suppressMessages -> withCallingHandlers -> library
Execution halted
2021-12-15 16:16:12,175 [INFO ]

Here is part of the message showed during the installation step of  
(mimseq) ~$ mamba install -c bioconda mimseq
...
  + r-base                                    4.1.1  hde4fec0_2           conda-forge/linux-64      25 MB
...

~$ conda activate mimseq
(mimseq) ~$ which mimseq
/home/yk/anaconda3/envs/mimseq/bin/mimseq
(mimseq) ~$ which R
/home/yk/anaconda3/envs/mimseq/bin/R
(mimseq) ~$ R --version
R version 4.1.1 (2021-08-10) -- "Kick Things"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-conda-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under the terms of the
GNU General Public License versions 2 or 3.
For more information about these matters see
https://www.gnu.org/licenses/.

(mimseq) ~$ mimseq --version
           _                 _   ____  _   _    _
 _ __ ___ (_)_ __ ___       | |_|  _ \| \ | |  / \   ___  ___  __ _
| '_ ` _ \| | '_ ` _ \ _____| __| |_) |  \| | / _ \ / __|/ _ \/ _` |
| | | | | | | | | | | |_____| |_|  _ <| |\  |/ ___ \\__ \  __/ (_| |
|_| |_| |_|_|_| |_| |_|      \__|_| \_\_| \_/_/   \_\___/\___|\__, |
                                                                 |_|

 Modification-induced misincorporation analysis of tRNA sequencing data

mimseq 0.4

###

**Comment by drewjbeh** [comment]
Hi there,

Thanks for reporting this! We are aware of the error and a new release will fix this. It is coming from from the reshape2 R dependency not being installed. For now, the simplest fix is to start R in you mimseq environment (by simply running `R`) and then installing the package with `install.packages("reshape2")`. You can then exit R and try rerunning your mimseq command.

Sorry for the inconvenience!

**Comment by cyken6621** [comment]
Hi Drew,

Thank you for the reply. It is fine now after installing the reshape2.

One more error that may be specific to my data.
I have a set of data containing 2 WT and 2 KO.
The DESeq2 analysis is interrupted with error and there is no heatmap  generated.
The  _diffexpr-countplot.pdf  files showed only 1 DEG (triangle) in anticodon and 0 DEG in isodecoder.

Here is  error message
Error in unit(x0, default.units) : 'x' and 'units' must have length > 0
Calls: rowAnnotation ... do.call -> <Anonymous> -> gList -> segmentsGrob -> unit
In addition: Warning messages:
1: In DESeqDataSet(se, design = design, ignoreRank) :
  some variables in design formula are characters, converting to factors
2: In DESeqDataSet(se, design = design, ignoreRank) :
  some variables in design formula are characters, converting to factors
3: Transformation introduced infinite values in continuous x-axis
4: Transformation introduced infinite values in continuous y-axis
5: Transformation introduced infinite values in continuous x-axis
6: It is deprecated to specify `guide = FALSE` to remove a guide. Please use `guide = "none"` instead.
7: Transformation introduced infinite values in continuous x-axis
8: Transformation introduced infinite values in continuous y-axis
9: Transformation introduced infinite values in continuous x-axis
10: It is deprecated to specify `guide = FALSE` to remove a guide. Please use `guide = "none"` instead.
Execution halted

From deseq.R in mimseq package, I guess the error is due to the low DEG numbers in generating the heatmap.
Perhaps, you would be able  to add some error-proof for this in the R script.

Thank you.
