### ISSUE TITLE
CalledProcessError: Command '['gsnap'.....] returned non-zero exit status 9.

### ISSUE THREAD

**Issue by AngLiRNA** [nedialkova-lab/mim-tRNAseq#27]
Hi,

Thank you for providing the great mim-tRNAseq.
When I used it, the cluster reported the error like this.

“2022-01-14 16:29:20,639 [INFO ] Aligning reads to Hsap_tRNAgenome...
Traceback (most recent call last):
  File "/home/al41/anaconda3/bin/mimseq", line 11, in <module>
    sys.exit(main())
  File "/home/al41/anaconda3/lib/python3.6/site-packages/mimseq/mimseq.py", line 381, in main
    args.misinc_thresh, args.mito, args.pretrnas, args.local_mod, args.p_adj, args.sampledata)
  File "/home/al41/anaconda3/lib/python3.6/site-packages/mimseq/mimseq.py", line 96, in mimseq
    snp_index_path, snp_index_name, out, threads, snp_tolerance, keep_temp, mismatches, map_round, remap)
  File "/home/al41/anaconda3/lib/python3.6/site-packages/mimseq/tRNAmap.py", line 48, in mainAlign
    unique_bam, librarySize, alignstats = mapReads(fq, genome_index_path, genome_index_name, snp_index_path, snp_index_name, threads, out_dir, snp_tolerance, keep_temp, mismatches, remap)
  File "/home/al41/anaconda3/lib/python3.6/site-packages/mimseq/tRNAmap.py", line 114, in mapReads
    subprocess.check_call(map_cmd, stderr = open(out_dir + "align.log", "a"))
  File "/home/al41/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)”
subprocess.CalledProcessError: Command '['gsnap', '--gunzip', '-D', 'hg38_WTvs1ko/Hsap_tRNAgenome', '-d', 'Hsap_tRNAgenome', '-V', 'hg38_WTvs1ko/Hsapsnp_index', '-v', 'hg38_test_modificationSNPs', '-t', '15', '--split-output', 'hg38_WTvs1ko/WT1', '--format', 'sam', '--genome-unk-mismatch', '0', '--md-lowercase-snp', '--ignore-trim-in-filtering', '1', '--indel-endlength', '0', '--max-mismatches', '0.1', './WT1.fastq.gz']' **returned non-zero exit status 9.**

I used this command.
mimseq --species Hsap38 --cluster-id 0.95 --threads 15 --min-cov 0.0005 --max-mismatches 0.1 --control-condition WT -n hg38_test --out-dir hg38_WTvs1ko --max-multi 4 --remap --remap-mismatches 0.075 /home/al41/data.txt

When I looked back about the align.log, it reported this error:"GSNAP version 2021-12-17 called with args: gsnap.avx512 --gunzip -D hg38_WTvs1ko/Hsap_tRNAgenome -d Hsap_tRNAgenome -V hg38_WTvs1ko/Hsapsnp_index -v hg38_test_modificationSNPs -t 15 --split-output hg38_WTvs1ko/WT1 --format sam --genome-unk-mismatch 0 --md-lowercase-snp --ignore-trim-in-filtering 1 --indel-endlength 0 --max-mismatches 0.1 ./WT1.fastq.gz
gsnap.avx512: unrecognized option '--ignore-trim-in-filtering'
For usage, run 'gsnap --help'"

Do you have some advices?
Thank you for your help.

Best,
Ang

**Comment by AngLiRNA** [comment]
It's works now, I guess it's the problem of the Gmap-version.

Thanks

**Comment by drewjbeh** [comment]
Hi Ang,

Thanks for the error report. Yes, indeed it seemed to be a GMAP version. Odd that your installation had that new version!
