### ISSUE TITLE
Run it for other species

### ISSUE THREAD

**Issue by AnneHoffmann** [nedialkova-lab/mim-tRNAseq#29]
Dear Drew,

I try to run the mim-tRNAseq Pipeline for organism which are not included in your species list. But it does not work. At the Modomics JSON data base there exists now entries for that species. 

mimseq -t Bs_tRNAscan.fa -o Bs_tRNAscan.out  --cluster-id 0.95 --threads 15 --min-cov 0.0005 --max-mismatches 0.1 --control-condition NC20 -n BSU20_test --out-dir BSU --max-multi 4 --remap --remap-mismatches 0.075 samples.txt

I always get the error:
Traceback (most recent call last):
  File "/home/anne.hoffmann/miniconda3/envs/mimseq/bin/mimseq", line 10, in <module>
    sys.exit(main())
  File "/home/anne.hoffmann/miniconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 405, in main
    args.misinc_thresh, args.mito, args.plant, args.pretrnas, args.local_mod, args.p_adj, args.sampledata)
  File "/home/anne.hoffmann/miniconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/mimseq.py", line 101, in mimseq
    = modsToSNPIndex(trnas, trnaout, mito_trnas, plant, modifications, name, out, double_cca, threads, snp_tolerance, cluster, cluster_id, posttrans, pretrnas, local_mod)
  File "/home/anne.hoffmann/miniconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 287, in modsToSNPIndex
    tRNA_dict[seq]['anticodon'] = anticodon = re.search('.*tR(NA|X)-.*?-(.*?)-', seq).group(2)
AttributeError: 'NoneType' object has no attribute 'group'

Thanks a lot

**Comment by drewjbeh** [comment]
Hi Anne,
Thanks for your message (and your great paper in 2018 which inspired some of the fundamental of mimseq by the way!). 

It can be tricky to get mimseq to work for species we have not pre-built references for. Unfortunately, mimseq relies quite heavily on very specific formatting of the fasta file headers for each tRNA. The naming needs to be consistent with that seen in other references, for example see [E. coli ](https://github.com/nedialkova-lab/mim-tRNAseq/blob/master/mimseq/data/eschColi-K_12_MG1655-tRNAs/eschColi_K_12_MG1655-tRNAs.fa). The naming of each gene, as well as the tRNAScan ID in "()" as well as other elements are important for mimseq to assign each gene to an anticodon, isodecoder and to find the correct gene in the "out" file for correct intron removal. 
If your fasta file is not formatted like this, it could be problematic. 

Which species are you working with? Would you mind sending me an example fasta input file so I can have a look? The best case scenario is that there are already predictions for these species on [GtRNAdb](http://gtrnadb.ucsc.edu/). If so, please download that data and use the fasta and out files as input for mimseq. This should already take care of many of the issues. If they are not on GtRNAdb, then you might have to parse the files to format them correctly, or request these species are added to GtRNAdb. I have been in contact with the maintainers of the database before for this reason and they are usually responsive and helpful.

Hope this helps!

**Comment by drewjbeh** [comment]
We don't work with bacteria so I didn't realise before, but GtRNAdb has predictions for 4037 bacterial genomes - I really hope your 3 are in there somewhere :)
