### ISSUE TITLE
usearch vs vsearch

### ISSUE THREAD

**Issue by TomSmithCGAT** [nedialkova-lab/mim-tRNAseq#31]
Thank you for this really cool looking pipeline, and the amazing method too!

I'm playing around with testing quantification approaches for tRNA-Seq datasets and wanted to include `mimseq`. 

Unfortunately, on an M1 mac, I get execution errors with `usearch`. I'm sure these could be debugged if I could compile `usearch` from source, but that doesn't seem to be an option, even for the 32-bit version. Regardless, it would seem beneficial to release `mimseq` from dependency on close-source software that the developer won't allow anyone else to distribute.

Would you have any objection to switching to [`vsearch`](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5075697/), which should be a drop-in replacement and can be installed via `conda` etc? 

I'm testing the switch to `vsearch` on my fork of this repo. What's the best way to test the consistency of the output?

**Comment by TomSmithCGAT** [comment]
Hi Drew.

I've not had much chance to progress this, but I've at least got a working version using vsearch on a fork: 

https://github.com/TomSmithCGAT/mim-tRNAseq/commit/7d2dfa8dc6e8d2bcaa69530c0dbb1893a1c09a0e

I ran with both v/usearch on the example HEK293 & K562 using the example command given in the README:
`mimseq --species Hsap --cluster-id 0.95 --threads 15 --min-cov 0.0005 --max-mismatches 0.1 --control-condition HEK293T -n hg38_test --out-dir hg38_HEK239vsK562 --max-multi 4 --remap --remap-mismatches 0.075 sampleData_HEKvsK562.txt` with the new option `--search` to specify which algorithm to use.

Looking into the `all_centroids.fa` file, the number of clusters and their identifiers change:

```bash
$ wc -l hg38_HEK239vsK562_*search/tmp/all_centroids.fa 
  604 hg38_HEK239vsK562_usearch/tmp/all_centroids.fa
  600 hg38_HEK239vsK562_vsearch/tmp/all_centroids.fa
```

Looking at individual example anticodons, it's not clear whether vsearch or usearch is 'better'. Taking a look at Arg-CCT as an example, there are two clusters which differ, with `usearch` giving 3 clusters for 5 sequences which `vsearch` puts into a single cluster. Given the edit distances between Homo_sapiens_tRNA-Arg-CCT-1-1 and all the other sequences is < 0.95, it seems the `vsearch` results are more sensible here. However, this isn't always the case.

```
diff <(grep '\-CCT' hg38_HEK239vsK562_usearch/tmp/all_centroids.fa|sort|sed 's/;$//g' ) <(grep '\-CCT' hg38_HEK239vsK562_vsearch/tmp/all_centroids.fa|sort)
1,3c1
< >Homo_sapiens_tRNA-Arg-CCT-2-1;size=3
< >Homo_sapiens_tRNA-Arg-CCT-3-1;size=1
< >Homo_sapiens_tRNA-Arg-CCT-5-1;size=1
---
> >Homo_sapiens_tRNA-Arg-CCT-1-1;size=5
```

Comparing the overall quantification, there's very little difference at the anticodon level:

![image](https://user-images.githubusercontent.com/6096414/178263198-52b0ea7a-a3de-484d-a426-12e6551d0e85.png)

But more of a difference at the isodecoder level, as you might expect:

![image](https://user-images.githubusercontent.com/6096414/178263339-e934614a-13f8-49ce-9a4a-14931ecdacf7.png)


There are slight differences in the number of new modifications identified (usearch=6, vsearch=8).

**Comment by TomSmithCGAT** [comment]
As an aside, I lost more time than I'd like to admit chasing what I thought was a bug with the GSNAP step but turned out to be my `mamba install -y -c bioconda vsearch` downgrading `pysam` to a very old version that threw an error at the BAM sort step :man_facepalming: . I guess that'll all be fine once the `mimseq` conda recipe includes `vsearch`, but worth being aware of if you try and just update an existing conda environment.

**Comment by drewjbeh** [comment]
Hi Tom,

Thanks so much for the analysis. 
Its a pity this wasn't easier and the results not more similar. The differences at the isodecoder level are a bit concerning, especially as they are not just a little off the diagonal, but really form some strange clusters in distinct "pockets" around the plot. How do the alignment stats change by the way? Do reads just get moved around or do we get more or less reads aligning in either of the methods?

The simulated data experiment sounds great, would be very interested in seeing how that goes. I might also have to make some time to run the vsearch test myself and investigate exactly what is changing. 

Thanks for the heads-up with dependency versioning error! Will be sure to keep an eye out for it. Hopefully a new conda recipe will handle it, but I have lost more time than I would like to admit trying to get conda recipes to work 🤦‍♂️ mimseq has a lot of dependencies unfortunately, and for conda this can be a big deal!

Thanks again!

**Comment by TomSmithCGAT** [comment]
Good question re mapping.

left = usearch, right=vsearch. Slightly higher proportion of uniquely mapped reads with vsearch.
```
$diff -y hg38_HEK239vsK562_usearch_all4/align/mapping_stats.txt  hg38_HEK239vsK562_vsearch_all/align/mapping_stats.txt

mimseq_hek_1.fastq.gz						mimseq_hek_1.fastq.gz
Uniquely mapped reads: 1603939 (80%) 			      |	Uniquely mapped reads: 1617359 (81%) 
Multi-mapping reads: 86091 (4%) 			      |	Multi-mapping reads: 72695 (4%) 
Unmapped reads: 309970 (15%) 				      |	Unmapped reads: 309946 (15%) 
Total: 2000000							Total: 2000000

mimseq_hek_2.fastq.gz						mimseq_hek_2.fastq.gz
Uniquely mapped reads: 1641427 (82%) 			      |	Uniquely mapped reads: 1655903 (83%) 
Multi-mapping reads: 90373 (5%) 			      |	Multi-mapping reads: 75851 (4%) 
Unmapped reads: 268200 (13%) 				      |	Unmapped reads: 268246 (13%) 
Total: 2000000							Total: 2000000

mimseq_k562_1.fastq.gz						mimseq_k562_1.fastq.gz
Uniquely mapped reads: 1644807 (82%) 			      |	Uniquely mapped reads: 1667261 (83%) 
Multi-mapping reads: 90761 (5%) 			      |	Multi-mapping reads: 67915 (3%) 
Unmapped reads: 264432 (13%) 				      |	Unmapped reads: 264824 (13%) 
Total: 2000000							Total: 2000000

mimseq_k562_2.fastq.gz						mimseq_k562_2.fastq.gz
Uniquely mapped reads: 1650385 (83%) 			      |	Uniquely mapped reads: 1676554 (84%) 
Multi-mapping reads: 104516 (5%) 			      |	Multi-mapping reads: 77786 (4%) 
Unmapped reads: 245099 (12%) 				      |	Unmapped reads: 245660 (12%) 
Total: 2000000							Total: 2000000

** NEW ALIGNMENT **						** NEW ALIGNMENT **

mimseq_hek_1.fastq.gz						mimseq_hek_1.fastq.gz
Uniquely mapped reads: 1650886 (83%) 			      |	Uniquely mapped reads: 1683305 (84%) 
Multi-mapping reads: 77309 (4%) 			      |	Multi-mapping reads: 45148 (2%) 
Unmapped reads: 271805 (14%) 				      |	Unmapped reads: 271547 (14%) 
Total: 2000000							Total: 2000000

** NEW ALIGNMENT **						** NEW ALIGNMENT **

mimseq_hek_2.fastq.gz						mimseq_hek_2.fastq.gz
Uniquely mapped reads: 1689101 (84%) 			      |	Uniquely mapped reads: 1723889 (86%) 
Multi-mapping reads: 81490 (4%) 			      |	Multi-mapping reads: 46843 (2%) 
Unmapped reads: 229409 (11%) 				      |	Unmapped reads: 229268 (11%) 
Total: 2000000							Total: 2000000

** NEW ALIGNMENT **						** NEW ALIGNMENT **

mimseq_k562_1.fastq.gz						mimseq_k562_1.fastq.gz
Uniquely mapped reads: 1696021 (85%) 			      |	Uniquely mapped reads: 1730874 (87%) 
Multi-mapping reads: 80300 (4%) 			      |	Multi-mapping reads: 46671 (2%) 
Unmapped reads: 223679 (11%) 				      |	Unmapped reads: 222455 (11%) 
Total: 2000000							Total: 2000000

** NEW ALIGNMENT **						** NEW ALIGNMENT **

mimseq_k562_2.fastq.gz						mimseq_k562_2.fastq.gz
Uniquely mapped reads: 1702971 (85%) 			      |	Uniquely mapped reads: 1738080 (87%) 
Multi-mapping reads: 90811 (5%) 			      |	Multi-mapping reads: 57094 (3%) 
Unmapped reads: 206218 (10%) 				      |	Unmapped reads: 204826 (10%) 
Total: 2000000							Total: 2000000
```

**Comment by drewjbeh** [comment]
Hmm very interesting, reads seem to go from multi-mapped to uniquely mapped. Unmapped doesn't change much. That's generally a good thing.
We have recently swopped to a cluster ID of 0.97 with the latest versions of mimseq (some new changes mean this gives what we think to be the most accurate results). And reduced mismatch tolerance (`--max-mismatches 0.075` and `--remap-mismatches 0.05`). You can see the example command in the git README and other docs as well. I wonder how this will affect the difference between vsearch and usearch?

**Comment by TomSmithCGAT** [comment]
Yeah, I'd spotted the update in the README command. I'll re-run with the updated tolerances and see how it looks

**Comment by TomSmithCGAT** [comment]
OK, so with the updated tolerances:

As you would expect, more clusters than before (604 & 600, respectively).
```
$ wc -l hg38_HEK239vsK562_*search_new/tmp/all_centroids.fa 
  687 hg38_HEK239vsK562_usearch_new/tmp/all_centroids.fa
  680 hg38_HEK239vsK562_vsearch_new/tmp/all_centroids.fa
```

Agreement at isodecoder level appears worse in the sense that there are more tRNAs with reasonable abundances that are a long way off the diagonal (I'm less concerned about what's going on with the very low abundance tRNAs). That's a very qualitative assessment though
![image](https://user-images.githubusercontent.com/6096414/178297887-4b35fc95-d523-4a26-bb24-5ae6d16292d2.png)


The alignment rates are lower and more similar using usearch and vsearch, with usearch very slightly higher. 

diff -y hg38_HEK239vsK562_usearch_new/align/mapping_stats.txt  hg38_HEK239vsK562_vsearch_new/align/mapping_stats.txt
mimseq_hek_1.fastq.gz						mimseq_hek_1.fastq.gz
Uniquely mapped reads: 1508953 (75%) 			      |	Uniquely mapped reads: 1492345 (75%) 
Multi-mapping reads: 81060 (4%) 			      |	Multi-mapping reads: 102564 (5%) 
Unmapped reads: 409987 (20%) 				      |	Unmapped reads: 405091 (20%) 
Total: 2000000							Total: 2000000

mimseq_hek_2.fastq.gz						mimseq_hek_2.fastq.gz
Uniquely mapped reads: 1542459 (77%) 			      |	Uniquely mapped reads: 1526107 (76%) 
Multi-mapping reads: 83939 (4%) 			      |	Multi-mapping reads: 105056 (5%) 
Unmapped reads: 373602 (19%) 				      |	Unmapped reads: 368837 (18%) 
Total: 2000000							Total: 2000000

mimseq_k562_1.fastq.gz						mimseq_k562_1.fastq.gz
Uniquely mapped reads: 1545660 (77%) 			      |	Uniquely mapped reads: 1530877 (77%) 
Multi-mapping reads: 75451 (4%) 			      |	Multi-mapping reads: 95168 (5%) 
Unmapped reads: 378889 (19%) 				      |	Unmapped reads: 373955 (19%) 
Total: 2000000							Total: 2000000

mimseq_k562_2.fastq.gz						mimseq_k562_2.fastq.gz
Uniquely mapped reads: 1566074 (78%) 			      |	Uniquely mapped reads: 1550877 (78%) 
Multi-mapping reads: 88394 (4%) 			      |	Multi-mapping reads: 110112 (6%) 
Unmapped reads: 345532 (17%) 				      |	Unmapped reads: 339011 (17%) 
Total: 2000000							Total: 2000000

** NEW ALIGNMENT **						** NEW ALIGNMENT **

mimseq_hek_1.fastq.gz						mimseq_hek_1.fastq.gz
Uniquely mapped reads: 1595347 (80%) 			      |	Uniquely mapped reads: 1580677 (79%) 
Multi-mapping reads: 72138 (4%) 			      |	Multi-mapping reads: 95642 (5%) 
Unmapped reads: 332515 (17%) 				      |	Unmapped reads: 323681 (16%) 
Total: 2000000							Total: 2000000

** NEW ALIGNMENT **						** NEW ALIGNMENT **

mimseq_hek_2.fastq.gz						mimseq_hek_2.fastq.gz
Uniquely mapped reads: 1632715 (82%) 			      |	Uniquely mapped reads: 1618713 (81%) 
Multi-mapping reads: 75408 (4%) 			      |	Multi-mapping reads: 98292 (5%) 
Unmapped reads: 291877 (15%) 				      |	Unmapped reads: 282995 (14%) 
Total: 2000000							Total: 2000000

** NEW ALIGNMENT **						** NEW ALIGNMENT **

mimseq_k562_1.fastq.gz						mimseq_k562_1.fastq.gz
Uniquely mapped reads: 1629749 (81%) 			      |	Uniquely mapped reads: 1613478 (81%) 
Multi-mapping reads: 65243 (3%) 			      |	Multi-mapping reads: 88181 (4%) 
Unmapped reads: 305008 (15%) 				      |	Unmapped reads: 298341 (15%) 
Total: 2000000							Total: 2000000

** NEW ALIGNMENT **						** NEW ALIGNMENT **

mimseq_k562_2.fastq.gz						mimseq_k562_2.fastq.gz
Uniquely mapped reads: 1645346 (82%) 			      |	Uniquely mapped reads: 1629130 (81%) 
Multi-mapping reads: 78280 (4%) 			      |	Multi-mapping reads: 102806 (5%) 
Unmapped reads: 276374 (14%) 				      |	Unmapped reads: 268064 (13%) 
Total: 2000000							Total: 2000000

**Comment by TomSmithCGAT** [comment]
I'll try mimseq with the previous and updated tolerances and u/vsearch and see how it looks with the simulated data. Probably won't get around to this for another week or so at least..

**Comment by drewjbeh** [comment]
Hi Tom,

Thanks a lot for the detailed tests. Very interesting that there are so many isodecoders off the diagonal. I agree that the more highly expressed ones are more important when looking for anomalies.
Hopefully the simulated data gives a clearer picture of what is more accurate. Does vsearch take exactly the same parameters and output the same files as usearch? Just trying to understand where the differences lie.
It might also be useful to inspect exactly which isodecoders are the ones far off the diagonal. And then case-by-case investigate the alignments in IGV or similar. This has been extremely useful in the past when debugging alignment issues. It can become obvious where there is misalignment or issues caused by modifications etc. 

Thanks again! Looking forward to the simulated data results. Also, there's really no rush, your help with this is very much appreciated.
