### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by kopardev** [nedialkova-lab/mim-tRNAseq#32]
Is there a docker for mim-tRNAseq?

**Comment by kopardev** [comment]
I created one [here](https://hub.docker.com/repository/docker/nciccbr/ccbr_mimseq). [This](https://github.com/CCBR/Dockers/blob/master/misc/mimseq/Dockerfile) is my recipe.

**Comment by drewjbeh** [comment]
Hi @kopardev,

Thanks a lot for making a docker image! Very helpful. 
I will test this and add it to the docs in case users would like to use Docker instead of conda
