### ISSUE TITLE
Dockerized mim-tRNAseq

### ISSUE THREAD

**Issue by joegeorgeson** [nedialkova-lab/mim-tRNAseq#40]
Dear mim-tRNAseq,

Any chance you've created a docker for this? if not, can you consider making one?

Thanks!

**Comment by drewjbeh** [comment]
Hi there,

Unfortunately there is no docker image for mim-tRNAseq yet. At the moment, we do not see a need for one either as installation using conda/bioconda has sufficed for most users.
Please feel free to generate one if you think the benefits are worth it. This should be fairly straightforward to build from the GitHub repository and using dependencies already specified for [bioconda](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/mimseq/meta.yaml)

**Comment by drewjbeh** [comment]
Hi there,

I will not get the report as I do not work for conda. I guess they will get this, but I'm not sure how much use it will be. Please note that I sent you a link to the yaml in case you needed it for preparing a docker container as it lists all the dependencies and required versions. I don't think the yaml is intended to be used in this way. If you install mimseq using conda (`conda install -c bioconda mimseq`) this is the yaml that gets used.

**Comment by joegeorgeson** [comment]
Hi there, thanks for your guidance. So I did previously build an environment where this worked with the addition of the aforementioned modules, but now for testing neither installation method (mamba nor bioconda) works for me. Does this work for you? Same behaviour on MacOS and CentOS. My conda channels are defined as [recommended by bioconda](https://bioconda.github.io/)

mamba fails with the below;
```
(mimseq) $ which mamba
/Users/opt/anaconda3/envs/mimseq/bin/mamba
(mimseq) $ mamba install -c bioconda mimseq
Traceback (most recent call last):
  File "/Users/opt/anaconda3/envs/mimseq/bin/mamba", line 7, in <module>
    from mamba.mamba import main
  File "/Users/opt/anaconda3/envs/mimseq/lib/python3.7/site-packages/mamba/mamba.py", line 53, in <module>
    from mamba.utils import get_index, to_package_record_from_subjson, _supplement_index_with_system
  File "/Users/opt/anaconda3/envs/mimseq/lib/python3.7/site-packages/mamba/utils.py", line 7, in <module>
    from .FastSubdirData import FastSubdirData
  File "/Users/opt/anaconda3/envs/mimseq/lib/python3.7/site-packages/mamba/FastSubdirData.py", line 23, in <module>
    from conda._vendor.auxlib.ish import dals
ModuleNotFoundError: No module named 'conda._vendor.auxlib'
```

and bioconda just hangs on 'Solving environment' and eventually times out;
```
$ conda create --name mimseq -c bioconda mimseq
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /
```

**Comment by joegeorgeson** [comment]
Can you export your mimseq conda to a yaml and copy here so I can try to install with `conda env create -f your_mimseq.yml` ?

**Comment by drewjbeh** [comment]
Did you try updating conda-build and mamba in the environment as proposed in the link I sent?

**Comment by drewjbeh** [comment]
It seems from the above you're not following the instructions we have detailed for creating the environment and installing the package in the readme for this repo and the documentation linked to it. Versions of python and other packages installed are important for the functioning of the package and it's proper and successful installation. Please follow the instructions, in this case there are definitely no package conflicts, as evidenced by many others successfully using mimseq. The whole point of a bioconda curated package is to ensure that these conflicts are solved.
