### ISSUE TITLE
Installation errors

### ISSUE THREAD

**Issue by pawanchk** [nedialkova-lab/mim-tRNAseq#49]
Hi,

Thank you for providing such a wonderful tool for analysing tRNA seq data. I am trying to install the tool but facing error in the last step (step 6) of installation using mamba. I have also tried the pip install process and installed dependencies but that ends in an Assertion error while running mimseq (please see below).

These are the steps that I have taken for the conda process of installation -
1. First I installed miniforge3 using `bash Miniforge3-Linux-x86_64.sh`

> This install mamba version 1.4.2

2. `conda create -n mimseq python=3.7`
3. `conda activate mimseq`

> Conda and mamba versions within the mimseq environment
mamba 1.4.2
conda 23.3.1

4. `conda config --add channels conda-forge`
5. `conda install -c conda-forge mamba`
6. `mamba install -c bioconda mimseq`

Step 6 ends with these warning and error msgs at the end 

> 

```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following packages are incompatible
└─ mimseq   is installable with the potential options
   ├─ mimseq 0.2.5.3 would require
   │  └─ biopython   with the potential options
   │     ├─ biopython [1.66|1.67|1.68|1.69|1.70] would require
   │     │  └─ python 2.7* , which can be installed;
   │     ├─ biopython [1.66|1.67|1.68|1.69|1.70] would require
   │     │  └─ python 3.5* , which can be installed;
   │     ├─ biopython [1.66|1.67|1.69|1.70] would require
   │     │  └─ python 3.6* , which can be installed;
   │     ├─ biopython 1.68 would require
   │     │  └─ python 3.4* , which can be installed;
   │     ├─ biopython [1.70|1.71|...|1.78] conflicts with any installable versions previously reported;
   │     ├─ biopython 1.79 conflicts with any installable versions previously reported;
   │     └─ biopython [1.80|1.81] conflicts with any installable versions previously reported;
   ├─ mimseq [0.2.5.4|0.2.5.5|...|0.3.4.1] would require
   │  └─ r-ggplot2 3.2.1.* , which conflicts with any installable versions previously reported;
   ├─ mimseq [0.3.4.3|0.3.4.5] would require
   │  └─ biopython 1.79.* , which conflicts with any installable versions previously reported;
   └─ mimseq [0.3.4.7|0.3.4.8|...|1.3.7] would require
      └─ biopython >=1.79 , which conflicts with any installable versions previously reported.
```

Can I please know how I can resolve these environment specs ?

I tried installing earlier versions of mamba (0.27.0) but that does not help also and ends in similar errors regarding environment specs when installing mimseq using mamba.

I also tried the pip install alternative process and also installed the dependencies (GSNAP, usearch) also but that ends in a different error (`AssertionError: group argument must be None for now`) as detailed in this issue post - https://github.com/nedialkova-lab/mim-tRNAseq/issues/33, so followed the conda process of installation as elaborated above.

Any suggestions will be very helpful.

**Comment by drewjbeh** [comment]
Hi there,

What maybe is not so clear from our side is that by installing mambaforge, one no longer needs to install mamba in the environment. Could you please try removing the environment you made altogether and recreate it, however this time please skip steps 4 and 5, and go straight to 6. 

Also, could you please copy the output of `which conda` here - I would like to double check that the correct installation of conda is being used. Thanks!

**Comment by pawanchk** [comment]
Hi,

Thank you so much for your prompt response, I appreciate it very much.

Regarding conda and it's version -
```
$ which conda
~/miniforge3/bin/conda
$ conda --version
conda 23.3.1
```

Do you think this conda version will work to install mimseq ? 
I will try re-creating the environment as you mentioned and update again. Thanks for your help.

**Comment by drewjbeh** [comment]
Hi,

 Yes versions look fine to me. Please try what I suggested (remove the environment with `conda env remove -n mimseq` and recreate it but skipping steps 4 and 5.

**Comment by pawanchk** [comment]
Thanks.

These are the steps I followed -

1. Remove the environment - `conda env remove -n mimseq`
2. Re-create the environment - `conda create -n mimseq python=3.7`
3. Activate the environment - `conda activate mimseq`
Versions within the mimseq environment -
```
$ mamba --version
mamba 1.4.2
conda 23.3.1
```

4. Install using -  `mamba install -c bioconda mimseq`
this step of installation ends with these lines -

```
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following packages are incompatible
└─ mimseq   is installable with the potential options
   ├─ mimseq 0.2.5.3 would require
   │  └─ biopython   with the potential options
   │     ├─ biopython [1.66|1.67|1.68|1.69|1.70] would require
   │     │  └─ python 2.7* , which can be installed;
   │     ├─ biopython [1.66|1.67|1.68|1.69|1.70] would require
   │     │  └─ python 3.5* , which can be installed;
   │     ├─ biopython [1.66|1.67|1.69|1.70] would require
   │     │  └─ python 3.6* , which can be installed;
   │     ├─ biopython 1.68 would require
   │     │  └─ python 3.4* , which can be installed;
   │     ├─ biopython [1.70|1.71|...|1.78] conflicts with any installable versions previously reported;
   │     ├─ biopython 1.79 conflicts with any installable versions previously reported;
   │     └─ biopython [1.80|1.81] conflicts with any installable versions previously reported;
   ├─ mimseq [0.2.5.4|0.2.5.5|...|0.3.4.1] would require
   │  └─ r-ggplot2 3.2.1.* , which conflicts with any installable versions previously reported;
   ├─ mimseq [0.3.4.3|0.3.4.5] would require
   │  └─ biopython 1.79.* , which conflicts with any installable versions previously reported;
   └─ mimseq [0.3.4.7|0.3.4.8|...|1.3.7] would require
      └─ biopython >=1.79 , which conflicts with any installable versions previously reported.
```

These errors are similar to what I got before, any suggestions on how to overcome these environment specs issues ?
Please let me know.

**Comment by drewjbeh** [comment]
Unfortunately, I am unable to recreate your error! I have tested this twice now from a fresh installation of conda and it has worked. It seems odd to me that a super old version of mimseq is trying to be installed (copied from your log):
`mimseq 0.2.5.3 would require`

Steps I recommend:
* Reinstall Miniforge (https://github.com/conda-forge/miniforge) - this time **NOT** Mambaforge as it seems this is discouraged as of last month.
* Retry the same steps as above (remove env, recreate, reinstall mimseq)
* If you get the same error, try `mamba install -c bioconda mimseq=1.3.7` to force the newest version of mimseq

**Comment by pawanchk** [comment]
I see. Am I possibly getting this error because I have `conda` installed from `anaconda3` as well ?  However before creating the `mimseq` environment I changed the base environment to miniforge3 base environment.

I installed `miniforge3` because I could not successfully install `mimseq` with the regular `conda` from `anaconda3`.

`conda env list` looks like this for me -
```
# conda environments:
#
                        ~/anaconda3
                        ~/anaconda3/envs/env1
                        ~/anaconda3/envs/env2
                        ~/anaconda3/envs/env3
                        ~/anaconda3/envs/env4
base                  *  ~/miniforge3
mimseq                  ~/miniforge3/envs/mimseq
```

Regarding your point 1., actually I have installed `miniforge3` and not `mambaforge` from the same link you have sent (https://github.com/conda-forge/miniforge). These are the steps I have followed to install `miniforge3` - download the https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge-pypy3-Linux-x86_64.sh and then run `bash Miniforge3-Linux-x86_64.sh`, `mamba 1.4.2` got installed at the end of the installation process by default.

So shall I proceed to force install the newest version of mimseq by creating a new environment as you have mentioned in points 2 and 3 rather than re-installing `miniforge3` ?

Please let me know.

**Comment by drewjbeh** [comment]
I don't think the error is from a previous installation of conda/anaconda - I have the same situation. We also already verified (`which conda`) that the correct new miniforge version is being used.
Your situation might be something similar to this: https://stackoverflow.com/questions/76512953/cannot-create-conda-environment-with-yaml. 
Please try add the conda-forge, bioconda, and defualts channels to your environment then install mimseq. Not sure if this will help.
Otherwise, do try install the newer version of mimseq with `mamba install -c bioconda mimseq=1.3.7`.
Failing that, please try reinstall miniforge anyway - perhaps a new installation can help and this should only take a few minutes (remember to log out and back into your shell/bash session after reinstallation).

**Comment by pawanchk** [comment]
Thank you for your suggestions.

Regarding this - "Please try add the conda-forge, bioconda, and defualts channels to your environment then install mimseq. Not sure if this will help."
This step should be carried out in a freshly created mimseq environment, am I correct ?

**Comment by drewjbeh** [comment]
Yes that looks good. According to that post, you may also try set channel_priority to flexible but I'm not sure this will help. Perhaps specifying mimseq version or reinstalling miniforge will help.

**Comment by pawanchk** [comment]
Hi,

Thanks for your suggestions. Changing the `channel_priority` to `flexible` seems to resolve the problem and `mimseq` v1.3.7 got installed finally. These were the last few lines of the installation process -

> 
```
Downloading and Extracting Packages

Preparing transaction: done
Verifying transaction: done
Executing transaction: /  
To install TinyTeX with `tinytex::install_tinytex()` the system must have a functional Perl
installation with a `File::Find` module. Most end-user systems will already satisfy this
requirement; however, some minimal contexts (e.g., containers) may not. Perl is available
via Conda Forge as the package `perl`. See https://github.com/rstudio/tinytex/issues/419
 

done
```

I tried running the demo dataset but without the `--local-modomics` option, it ended with the `KeyError: 'Ζ'` as elaborated in this issue https://github.com/nedialkova-lab/mim-tRNAseq/issues/45

With the `--local-modomics` option, the demo dataset analysis finished successfully but there were lot of warnings with the R packages especially in the `Final deconvolution and filtering` and `3' CCA analysis` section

```
+-----------------------------------+           
| Final deconvolution and filtering |           
+-----------------------------------+
Warning message:
package ‘ggplot2’ was built under R version 4.2.3 
Warning message:
package ‘reshape2’ was built under R version 4.2.3 
Warning message:
package ‘gridExtra’ was built under R version 4.2.3 
Warning message:
package ‘plyr’ was built under R version 4.2.3 
Failed to create bus connection: No such file or directory
Warning messages:
1: In system("timedatectl", intern = TRUE) :
  running command 'timedatectl' had status 1
2: package ‘tibble’ was built under R version 4.2.3 
3: package ‘tidyr’ was built under R version 4.2.3 
4: package ‘readr’ was built under R version 4.2.3 
5: package ‘purrr’ was built under R version 4.2.3 
6: package ‘dplyr’ was built under R version 4.2.3 
7: package ‘stringr’ was built under R version 4.2.3 
8: package ‘forcats’ was built under R version 4.2.3 
Warning message:
package ‘circlize’ was built under R version 4.2.3 
Warning message:
package ‘RColorBrewer’ was built under R version 4.2.3 
`summarise()` has grouped output by 'condition'. You can override using the
`.groups` argument.
`summarise()` has grouped output by 'condition'. You can override using the
`.groups` argument.
There were 50 or more warnings (use warnings() to see the first 50)
```

Please find attached the complete log file for your reference.

The Rplots.pdf file in the analysis directory is currently empty, any suggestions on how to overcome these R packages issues ?

Please let me know.
[demo_data_analysis_log.txt](https://github.com/nedialkova-lab/mim-tRNAseq/files/13184485/demo_data_analysis_log.txt)

**Comment by drewjbeh** [comment]
Hi there,

Great news that you got it working. The Rplots.pdf should be empty, it is sometimes output by R at the end of a script when the display device is disconnected. You can ignore this.

As for the other R warnings, they are just that; warnings not errors. You should still have a complete run with all plots and results? This warning is saying that the packages being used were built under R v4.2.3 but your base R version is different (can check this by running `R --version` in your environment). I'm not sure why this is the case or how to properly fix it but perhaps down- or upgrading R to match v4.2.3 might help. Do this at your own risk!

**Comment by pawanchk** [comment]
Thanks for your response and clarifications again, I appreciate it.

Yes, I have multiple output folders and results for the demo data --
```
mods
mods_logOR
CCAanalysis
DESeq2
mim-tRNAseq_17-22-21.log
indices
cov
counts
annotation
align
```

`R --version` within the `mimseq` environment is `4.2.1` and the packages used are from `4.2.3` so that's the reason of the warning msgs generated I assume. Also, if this is not really a big concern then there is no need to upgrade the R version (I guess).

The only other thing I noticed is this msg - `Failed to create bus connection: No such file or directory` in the `Final deconvolution and filtering` section, is this of any concern ?

**Comment by pawanchk** [comment]
Hi Drew,

Besides my previous question about the R related msg in the `Final deconvolution and filtering` step which is `Failed to create bus connection: No such file or directory` (please see my earlier post), I have two additional questions -

1. Can `mim-tRNAseq` work with single end sequencing data ?
2. Can fasta files be used as input rather than fastq files ?

Please let me know.

**Comment by nedialkova-lab** [comment]
Hi there, you can find answers to common questions listed about the pipeline here: https://www.sciencedirect.com/science/article/pii/S2666166722004592?via%3Dihub

**Comment by drewjbeh** [comment]
As for the `Failed to create bus connection: No such file or directory`, this seems to be something specific to the server you are running on, potentially related to `dbus` or `timedatectl`:

https://unix.stackexchange.com/questions/560859/hostnamectl-shows-error-failed-to-create-bus-connection-no-such-file-or-direc

**Comment by drewjbeh** [comment]
Indeed potentially something related to the time and date or timezone settings on your machine 

https://stackoverflow.com/questions/71817480/failed-to-create-bus-connection-running-command-timedatectl-had-status-1

**Comment by pawanchk** [comment]
Thanks Drew,
If it's just a timezone settings then not a big concern I guess. I was concerned like maybe some result file does not get generated because of this error.

Also, can I please get your opinion about these two queries -
1. Can mim-tRNAseq work with single end sequencing data ?
2. Can fasta files be used as input rather than fastq files ?

**Comment by nedialkova-lab** [comment]
Hi there - again, you can find answers to common questions like these in our paper here: https://www.sciencedirect.com/science/article/pii/S2666166722004592?via%3Dihub.
