### ISSUE TITLE
Set up E2E test with continuous integration

### ISSUE THREAD

**Issue by kelly-sovacool** [nedialkova-lab/mim-tRNAseq#58]
Hi @drewjbeh! Sorry for the flurry of PRs -- we have collaborators wanting to use our pipeline which depends on your tool, and so I'm hoping to help fix the breaking changes that have occurred recently.

Do you have interest in setting up a testing framework with continuous integration? If so, I'm happy to help do that. Getting this setup would allow you to detect when breaking changes occur and prevent bad PRs from being merged in the first place.

Let me know, thanks!

**Comment by drewjbeh** [comment]
Hi @kelly-sovacool 

Great idea in general, and thank you for the kind offer. The only problem is I have moved on from the Nedialkova lab and might not really have any more time to maintain this package. We hoped that some form of "final" stable release would be functional for some time into the future (hopefully the next release will be so ), and that without any more planned addition of functionality, there would be less breaking changes (of course, if MODOMICS keep changing things without telling anyone this can be tough to avoid!). 

Apart from the past couple of weeks, there have been less and less issues coming through and more stable use of mim-tRNAseq so I hope this can continue. We also haven't had huge numbers of contributors recently or in the past, and it has been almost entirely me contributing (and testing), so the need wasn't quite there. 

If you feel this is necessary, and especially if you plan to continue to contribute to the pipeline, then I will be happy to help where my availability allows! Let me know what you think.

**Comment by kelly-sovacool** [comment]
Thanks for your openness, Drew. I think getting this set up would be even more worthwhile to save you time and effort as you're trying to step back from maintaining the package. I'll draft a PR with a minimal E2E test using GitHub Actions, and we can go from there.

**Comment by drewjbeh** [comment]
Thank you for your efforts @kelly-sovacool !
