### ISSUE TITLE
modifications outdated?

### ISSUE THREAD

**Issue by piechottam** [nedialkova-lab/mim-tRNAseq#64]
Dear authors, thank you for the useful toll!

I am trying to run it on human:
```
mimseq \
  --species Hsap \
  --cluster-id 0.97 \
  --threads $THREADS \
  --min-cov 0.0005 \
  --max-mismatches 0.075 \
  --control-condition $COND \
  -n $NAME \
  --out-dir output_default \
  --max-multi 4 \
  --remap \
  --remap-mismatches 0.05 \
  --no-cca-analysis \
  $SAMPLE_DESC
```
Ang I get the following error:
```python
[...]
  File "/home/mpiechotta/miniconda3/envs/mimseq/lib/python3.7/site-packages/mimseq/tRNAtools.py", line 930, in getUnmodSeq
    char = modification_table[char]['ref']
KeyError: 'ʤ'
```
It indicates file `mimseq/modifications` that is included in the package is missing this particular modification `ʤ`.
Can I overwrite this file with a modified version of: `www.genesilico.pl/modomics/api/modifications`?

**Comment by nedialkova-lab** [comment]
Hi there - please see #45, the MODOMICS team have done an overhaul of symbol use in their database but have not updated the API to be compatible with the modification abbreviations in their tRNA sequences. Once this is done there will be a new version of mimseq - until then, you can use the --local-modomics option.

**Comment by drewjbeh** [comment]
Please note that editing any source files/data from mimseq is done at your own risk. For example, editing the `mimseq/modifications` file will ensure that neither the normal default settings (obtaining sequences through MODOMICS API), nor the `--local-modomics` option mentioned above will work.

The folks at MODOMICS have almost updated everything needed in the APIs (both modifications and tRNA sequences) for mimseq to work. New version coming soon!
