### ISSUE TITLE
GSNAP Ver. 2019-02-26 Installation issues

### ISSUE THREAD

**Issue by Futa0908** [nedialkova-lab/mim-tRNAseq#66]
Hello there, I am glad to meet you. 
I have a problem installing GMAP-GSNAP on the terminal(Ubuntu). I installed GMAP Ver 2019-02-26 as per protocol instructions but got the following error.

error >>>
 /usr/bin/ld: gmap_avx2-dynprog_end.o:(.bss+0x0): multiple definition of `homopolymerp'; gmap_avx2-dynprog_single.o:(.bss+0x0): first defined here

I can't compile Makefile properly due to duplicate variable definitions, please let me know if you know how to solve this problem, I have tried many ways but I can't get it to work. I followed the following steps on the terminal." All modules except "GMAP" were installed correctly.

Operating Procedure >>>

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1,  wget http://research-pub.gene.com/gmap/src/gmap-gsnap-2019-02-26.tar.gz
2, tar xzvf  gmap-gsnap-2019-02-26.tar.gz
3, cd gmap-2019-02-26
4, ./configure --prefix= ~/....../...../gmap-2019-02-26
5, make    ------> 　At this stage, the above error occurs.
---------------------------------------------------------------
6, make check
7, make install

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

If you know anything at all about this matter, please let me know !!!

Ubuntu 22.04.3 LTS /// 13 th Gen Intel Core i9-13900K x 32 /// GPU NVIIDIA 3060RTX

**Comment by nedialkova-lab** [comment]
Hi there - we recommend installing mimseq using the [Miniforge](https://github.com/conda-forge/miniforge) version of conda. Then GSNAP should be included in the dependencies and you would not have to install it separately.

**Comment by Futa0908** [comment]
Thanks for your reply!
I created a new development environment and installed mim_seq and it works correctly!

Really helpful, THANK YOU!!!!!!!!!!!!!!! :)
