### ISSUE TITLE
The question for isodecoders cluster.

### ISSUE THREAD

**Issue by YinanLi07** [nedialkova-lab/mim-tRNAseq#75]
Hello. Thank you for your excellent tool. I have a question that I would like to consult. How can isodecoders be clustered? I have tRNA-seq data at three time points, namely 0h_vs_3h and 3h_vs_6h. There are differences in the clustering results of Ser-AGA in the output files.  How can this problem be solved?

**Comment by drewjbeh** [comment]
Hi! I'm not sure I understand the question or the error. What do you mean by the clustering results are different for Ser-AGA? The clustering of the isodecoders works based on sequence, this means it happens exactly the same way every time if the input tRNA sequences and the clustering parameters are kept constant.

**Comment by YinanLi07** [comment]
Hi! Thank you for your reply.


I have tRNA - seq data for three time - points, 0h_vs_3h and 3h_vs_6h. In 0h_vs_3h, Ser - AGA can be clustered into Ser-AGA-1, Ser-AGA-4 and Ser-AGA-2/3/7. However, in 3h_vs_6h, the clustering results have changed to Ser-AGA-1 and Ser-AGA-2/3/4/7.


I haven't modified any parameters except for the names of the output files and the input samples, but the clustering results have changed, and I've been very puzzled about this.


| |
liyn02232023
|
|
***@***.***
|
---- Replied Message ----
| From | Drew ***@***.***> |
| Date | 12/10/2024 19:37 |
| To | ***@***.***> |
| Cc | Yinan ***@***.***>,
***@***.***> |
| Subject | Re: [nedialkova-lab/mim-tRNAseq] The question for isodecoders cluster. (Issue #75) |

Hi! I'm not sure I understand the question or the error. What do you mean by the clustering results are different for Ser-AGA? The clustering of the isodecoders works based on sequence, this means it happens exactly the same way every time if the input tRNA sequences and the clustering parameters are kept constant.

**Comment by drewjbeh** [comment]
Ok I understand. This is not the clustering but the deconvolution that is
different between the runs. This can be data dependent as the deconvolution
process is data driven which differs at different positions in different
libraries.
However, this difference should only be the case if you are running your
time points as separate mimseq runs. Is that the case? If so, this is
incorrect and a waste of time. Simply put all your samples in one sample
sheet and run them together.
Additionally, "0h_vs3h" is not a timepoint but a comparison between two
time points. If I understand and your time points are in fact 0h, 3h and
6h, then put all samples in the sample sheet with these labels and mimseq
will automatically make all possible pairwise  comparisons of these
timepoints for you

**Comment by YinanLi07** [comment]
Thank you very much! I only saw the "sampleData_HEKvsK562.txt" in the documentation, so I thought that only pairwise comparisons were possible and didn't consider that multiple samples could be analyzed simultaneously.  



| |
liyn02232023
|
|
***@***.***
|
---- Replied Message ----
| From | Drew ***@***.***> |
| Date | 12/10/2024 19:57 |
| To | ***@***.***> |
| Cc | Yinan ***@***.***>,
***@***.***> |
| Subject | Re: [nedialkova-lab/mim-tRNAseq] The question for isodecoders cluster. (Issue #75) |
Ok I understand. This is not the clustering but the deconvolution that is
different between the runs. This can be data dependent as the deconvolution
process is data driven which differs at different positions in different
libraries.
However, this difference should only be the case if you are running your
time points as separate mimseq runs. Is that the case? If so, this is
incorrect and a waste of time. Simply put all your samples in one sample
sheet and run them together.
Additionally, "0h_vs3h" is not a timepoint but a comparison between two
time points. If I understand and your time points are in fact 0h, 3h and
6h, then put all samples in the sample sheet with these labels and mimseq
will automatically make all possible pairwise comparisons of these
timepoints for you
